name: Merge to master and release to pypi

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    if: github.actor == 'miigotu'
    steps:
      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.prepare.outputs.npm_cache }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Restore pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.prepare.outputs.pip_cache }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Restore tox workdir
        uses: actions/cache@v2
        with:
          path: $(tox --showconfig | grep '^toxworkdir = .*$' | tail -c+14)
          key: ${{ runner.os }}-tox-${{ hashFiles('**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel twine tox
          npm config set strict-ssl false
          npm config set registry "http://registry.npmjs.org/"
          npm install -D
          npm install -g grunt bower xo
      - name: Checkout changelog repo
        uses: actions/checkout@v2
        with:
          repository: sickchill/sickchill.github.io
          path: sickchill/sickchill.github.io
      - name: Checkout SickChill
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
          path: sickchill
      - name: Test with XO
        run: xo
      - name: Test with tox
        id: tox
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          tox -v --recreate -e "py38-{flake8,${{ steps.prepare.outputs.os }}}"
      - name: Publish
        env:
          SICKCHILL_CHANGES_FILE: "sickchill.github.io/sickchill-news/CHANGES.md"
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        working-directory: sickchill
        run: |
          git config --global user.name miigotu
          git config --global user.email miigotu@gmail.com
          grunt publish
          git checkout master
          python setup.py sdist bdist_wheel
          twine upload dist/*
          VERSION=$(grep -oP "\d{4}\.\d{1,2}\.\d{1,2}\.post\d*" sickchill/version.py)
          git commit -asm "Release $VERSION to pypi"
          git push origin master
          git checkout develop
          git reset --hard master
          git push origin develop
